### ISSUE TITLE
ui.py error on colab

### ISSUE THREAD

**Issue by softmurata** [Jun-CEN/SegmentAnyRGBD#1]
Thanks for great work!
I would like to ui.py on google colab.
but, when I ran it, I met the following error on GradIO

`Unexpected token '<', "<html> <h"... is not valid JSON`

On Google colab console
```
['/tmp/c0c30d2f119e2c9f55e079cff868436b0489eb5d/tmpawyn8wax.png']
  0% 0/1 [00:00<?, ?it/s]Using SAM to generate segments for the RGB image
Using SAM to generate segments for the Depth map
  0% 0/1 [01:06<?, ?it/s]
```
SARGBD cannot generate RGB image for semantic segmentation... 

Please tell me how to solve this problem.

**Comment by Jun-CEN** [comment]
Hi,

Thanks for your interest! I have not tried ui.py on Colab. Could you please share the code here? Since I am not sure what's wrong based on the problem you discribe.
